[phases.setup]
nixPackages = ["python312", "pip", "nodejs_18"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[start]
cmd = "python3 -m uvicorn MultiBroker_Router:app --host 0.0.0.0 --port $PORT"
